# Generated by Django 4.2.5 on 2024-02-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_userinfo_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='bankinfo',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='account_holder',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='account_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bankname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='BankInfo',
        ),
    ]
