# Generated by Django 4.2.5 on 2024-02-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_userinfo_bankinfo_userinfo_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
