# Generated by Django 4.2.5 on 2024-05-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_brand_product_categories_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
