name: execute tests
run-name: tests execution
on:
  pull_request:
    branches: [master]
jobs:
  echo_header:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Header
        run: echo "Running Tests"

  run_tests:
    needs: echo_header
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup Virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Setup Variables Env
        run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env

      - name: Run migrations
        run: pipenv run python manage.py migrate --fake-initial

      - name: Run tests
        run: pipenv run python manage.py test tests
